### ISSUE TITLE
uses 3 much memory

### ISSUE THREAD

**Issue by HotelCalifornia** [HotelCalifornia/x64#2]
turns out that having the bot in a server with more than 200 users (plus who knows how many other servers) is a little too much to audit every single message the bot has permission to view and spawn a 200MB JVM instance for each one 🤔 

possible solutions:
 - rate limit shitposting command
    - pros:
      - easy
    - cons:
      - where's the fun in that?
 - actually port tagger to golang
    - pros:
      - could greatly reduce amount of memory used
    - cons:
      - hard
      - not clear if it will actually do anything to solve the problem
 - upgrade vps:
    - pros:
      - easy
    - cons:
      - costs money

**Comment by HotelCalifornia** [comment]
even better solution:

instead of running the process from scratch each time, invoke one process and use sockets n' stuff to route data.

can't believe I didn't think of this a year ago

**Comment by HotelCalifornia** [comment]
turns out the stanford NLP thingy also has a server mode. See hotelcalifornia/x128

**Comment by JoneSGirL1111** [comment]
![57b6fbf4adfb224fba9bd7c15e1da847.jpg](https://user-images.githubusercontent.com/71618779/94654070-87cde880-02ca-11eb-8285-5b858ce4fcfe.jpg)
